---
- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Create root password for DB
  mysql_user:
    name: root
    login_unix_socket: /var/lib/mysql/mysql.sock
    password: '{{ root_db_password }}'
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  notify: 
   - restart dbservice

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600


- name: check if /var/lib/mysql/icinga exists
  stat: 
    path: /var/lib/mysql/icinga
  register: icingaDB_file

- name: Import icinga2db from sql schema
  mysql_db:
    state: import
    name: '{{ icinga2db_name }}'
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  when: icingaDB_file.stat.exists==false

- name: Removes anonymous user account for localhost
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: ''
    host: localhost
    state: absent

- name: Create database user icinga with pass icinga
  mysql_user:
    name: '{{ icinga2db_user }}'
    password: '{{ icinga2db_password }}'
    priv: 'icinga.*:ALL'
    state: present

- name: Create a new database 'icingawebdb'
  mysql_db:
    name: icingawebdb
    state: present

- name: Create database user icinga with pass icinga
  mysql_user:
    name: '{{ icinga2web_user }}'
    password: '{{ icinga2web_password }}'
    priv: 'icingawebdb.*:ALL'
    state: present
