---
#none of this users is webuser for login, this account is created from GUI
icinga2db_user: icinga
icinga2db_password: icinga
icinga2db_name: icinga
root_db_password: Tazkeheslo1.
icinga2web_user: icingaweb
icinga2web_password: icinga123
packages:
 - python3-pip
 - icinga2
 - icinga2-selinux
 - mariadb-server
 - mariadb
 - icinga2-ido-mysql
 - php-json
 - icingaweb2
 - icingacli
 - httpd
 - nagios-plugins-apt
 - nagios-plugins-breeze
 - nagios-plugins-by_ssh
 - nagios-plugins-cluster
 - nagios-plugins-dbi
 - nagios-plugins-dhcp
 - nagios-plugins-dig
 - nagios-plugins-disk
 - nagios-plugins-dns
 - nagios-plugins-dummy
 - nagios-plugins-file_age
 - nagios-plugins-flexlm
 - nagios-plugins-fping
 - nagios-plugins-hpjd
 - nagios-plugins-http
 - nagios-plugins-icmp
 - nagios-plugins-ide_smart
 - nagios-plugins-ircd
 - nagios-plugins-ldap
 - nagios-plugins-load
 - nagios-plugins-log
 - nagios-plugins-mailq
 - nagios-plugins-mrtg
 - nagios-plugins-mrtgtraf
 - nagios-plugins-mysql
 - nagios-plugins-nagios
 - nagios-plugins-nrpe
 - nagios-plugins-nt
 - nagios-plugins-ntp
 - nagios-plugins-nwstat
 - nagios-plugins-oracle
 - nagios-plugins-overcr
 - nagios-plugins-perl
 - nagios-plugins-pgsql
 - nagios-plugins-ping
 - nagios-plugins-procs
 - nagios-plugins-radius
 - nagios-plugins-real
 - nagios-plugins-remove_perfdata
 - nagios-plugins-rpc
 - nagios-plugins-sensors
 - nagios-plugins-smtp
 - nagios-plugins-snmp
 - nagios-plugins-ssh
 - nagios-plugins-swap
 - nagios-plugins-tcp
 - nagios-plugins-time
 - nagios-plugins-ups
 - nagios-plugins-uptime
 - nagios-plugins-users
 - nagios-plugins-wave

